### ISSUE TITLE
Support for Instanced Pipelines in Details Link

### ISSUE THREAD

**Issue by drewcarmichael-okta** [Pix4D/cogito#36]
Regular pipelines Url 
https://concourse.example.net/teams/straw-man-github_status/pipelines/topic/jobs/initialize/builds/40

Instanced Pipeline URL
https://flying-pig-dev.aue1f.saasure.net/teams/starfall-straw-man-github_status/pipelines/topic/jobs/initialize/builds/40?vars.branch=%22added_hooks%22

Currently the details link does not allow for any info to be passed

**Comment by lsjostro** [comment]
@drewcarmichael-okta #26 fixes this. And if you can't wait till it's merged check out the last comment. https://github.com/Pix4D/cogito/pull/26#issuecomment-795452605

**Comment by drewcarmichael-okta** [comment]
@lsjostro  thanks
