### ISSUE TITLE
Feature request: configurable description

### ISSUE THREAD

**Issue by rosenhouse** [Pix4D/cogito#41]
Hello!

Thanks for making this resource, I'm using it a ton and it's working great.

I'd love to be able to do something like
```
put: my-commit-status
params:
  ...
  description: "my custom description"
```

That field would be optional, and if not set, would default to [the current behavior of `"Build " + buildN`](https://github.com/Pix4D/cogito/blob/46e24d86e397790f5a5135db35e23c19c03002d0/resource/resource.go#L236).

I'm willing to try to PR that in, if there's interest.

Thanks!

**Comment by marco-m-pix4d** [comment]
Hello,
thanks for the kind words :-)

Regarding your request, although not really the same, it is already possible to customize the optional `context_prefix` in the source stanza and `context` for the put step. Would that be enough?

**Comment by rosenhouse** [comment]
Hi, sorry for the delay.  If I recall, your suggestion above didn't quite fit my use-case.  But also, we're still using the resource in our pipeline, and its working well, and I'm busy with other things.  So, maybe I should just close this!
