### ISSUE TITLE
Support for Enterprise Github?

### ISSUE THREAD

**Issue by olwenya** [Pix4D/cogito#51]
Does this line mean that for Enterprise Github (not github.com) will now work?

https://github.com/Pix4D/cogito/blob/50a9d9656fed99e13f7c83fc3487e3c3500ef687/resource/resource.go#L378

```
fetching pix4d/cogito@sha256:cef4adfe17e9ee5f7c16a4094e435d88857f663f080507dcb6b61e7390b52852
29291e31a76a [==========================================] 2.7MiB/2.7MiB
ff9cc595764e [======================================] 274.7KiB/274.7KiB
60eff1c2ce14 [==============================================] 116b/116b
507e2309724c [==========================================] 5.9MiB/5.9MiB
This is the Cogito GitHub status resource. Tag: 0.6.0, commit: 5d34381a18, build date: 2021-08-26
resource source configuration and git repository are incompatible.
Git remote: "https://notgithub.com/xxx/xxx.git"
Resource config: host: github.com, owner: "xxx", repo: "xxx". wrong git remote
```

**Comment by marco-m-pix4d** [comment]
Looking into this, there are two parts involved:

- The API endpoint, that should be `https://{hostname}/api/v3` according to [Getting started with the REST API](https://docs.github.com/en/enterprise-server/rest/guides/getting-started-with-the-rest-api).
- The Git remote, that should be `https://{hostname}/{owner}/{repo}.git`.

**Comment by marco-m-pix4d** [comment]
@olwenya could you please confirm that the only difference is the `{hostname}`, both to access the API and to refer to the git remote ? See https://github.com/Pix4D/cogito/issues/51#issuecomment-1012300930

**Comment by wanderanimrod** [comment]
> @olwenya could you please confirm that the only difference is the {hostname}, both to access the API and to refer to the git remote ? See https://github.com/Pix4D/cogito/issues/51#issuecomment-1012300930

@marco-m-pix4d , this is correct.

**Comment by wanderanimrod** [comment]
@marco-m-pix4d , FYI
I cloned this repo, replaced all the `github.com` references with our enterprise GitHub domain, built an image and tested it. It worked! I haven't pushed the changes to my fork because the tests are broken, and I need to parameterize the GH host instead of hard coding it in. 

Do you think the host should become another config option on the resource's `source` (defaulting to `github.com`)?
